### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by obsgolem** [obsgolem/rusty-radar#1]
This is a list of tasks that need done before this is really usable for anything:
* [ ] Expand scene capability
    * [ ] Ground clutter (constant gamma to begin with)
* [ ] V&V for radar propagation equations
* [ ] V&V of antenna code
* [ ] Configuration language
* [ ] Table based radar signatures
* [ ] Complex-valued radar signatures (maybe?)
* [ ] Citations for signal library
* [ ] Detection of target in vacuum
    * [ ] Noise reduction
* [ ] Advanced radar signal processing
    * [ ] Pulse-doppler/Delay-line MTI
    * [ ] STAP
* [ ] Output plots

Low priority:
* [ ] IIR filter library
* [ ] Round earth

**Comment by jason-ivey** [comment]
Very cool project, good luck!
